
info:
  profile: default
logging:
  config: classpath:logback.xml
eureka: 
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:2001/eureka/
server:
  port: 9090
spring:
  profiles:
    active: default
  application:
    name: dao
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver 
  redis:
    host: 192.168.3.7
    port: 6379
    password: 123456
    pool:
      max-active: 8
      max-wait: 15000
      max-idle: 8
      min-idle: 0
  zipkin:
    base-url: http://192.168.3.7:9411
# 易宝请求地址
yeepay:
  # 异步回调
  callback:
    paymentUrl: 'http://115.236.176.90:8889/yeepay-server/ybpayment/callback/async/'
