
info:
  profile: default
logging:
  config: classpath:logback.xml
eureka: 
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:2001/eureka/
server:
  port: 9090
spring:
  profiles:
    active: default
  application:
    name: yeepay-server
  datasource:
    primary:
      name: primary
      url: jdbc:mysql://192.168.3.6:3306/qurong_payment?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      validation-query: SELECT 1
      max-open-prepared-statements: 20
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      max-wait: 60000
      max-active: 20
      min-idle: 15
      min-evictable-idle-time-millis: 300000
      login-username: payment
      login-password: 'payment123!@#'
  redis:
    host: 192.168.3.7
    port: 6379
    password: 123456
    pool:
      max-active: 8
      max-wait: 15000
      max-idle: 8
      min-idle: 0
  zipkin:
    base-url: http://192.168.3.7:9411
# 易宝请求地址
yeepay:
  # 异步回调
  callback:
    paymentUrl: 'http://115.236.176.90:8889/yeepay-server/ybpayment/callback/async/'
