info:
  profile: default
logging:
  config: classpath:logback-spring.xml
eureka: 
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:2001/eureka/
server:
  port: 5010
spring:
  profiles:
    active: default
  application:
    name: model
 
